server:
  port: 8888
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dm?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 15239440831
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: mwHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
# MyBatis配置
mybatis:
  # mybatis配置文件的路径
  # config-location:
  mapper-locations: com/fc/mapper/*.xml
  type-aliases-package: com.fc.entity
  configuration:
    # 二级缓存
    cache-enabled: true
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 主键回填
    use-generated-keys: true
    # 懒加载
    lazy-loading-enabled: true
    # 积极加载
    aggressive-lazy-loading: false
    # 驼峰命名
    map-underscore-to-camel-case: true
